services:
  backend:
    build:
      context: ./codiceglobal_back/api
      dockerfile: Dockerfile
    container_name: codice_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./codiceglobal_back/api:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./codiceglobal_front
      dockerfile: Dockerfile
    container_name: codice_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      # VITE_BACKEND_URL=http://backend:5000  <-- use this inside React!
    volumes:
      - ./codiceglobal_front:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    name: codice_network
