name: Deploy Frontend
on:
    push:
        branches:
        - main
jobs:
    build-and-deploy-front:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v6
          with:
            node-version: '20.x'
            node-version-file: ./front/package.json
            cache: 'pnpm'
            cache-dependency-path: ./front/pnpm-lock.yaml

        - name: Install dependencies
          run: pnpm install
          working-directory: ./front

        - name: Build frontend
          run: pnpm build
          working-directory: ./front

        - name: Test frontend
          run: pnpm test
          working-directory: ./front
        - name: Deploy in Heroku
          run: |
            curl https://cli-assets.heroku.com/install.sh | sh 
        - uses: akhileshns/heroku-deploy@v3.14.15
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            healthcheck: "https://${{secrets.HEROKU_APP}}/health"
            rollbackonhealthcheckfailed: true
        
        